### ISSUE TITLE
How to have multilingual with client-only routes?

### ISSUE THREAD

**Issue by alveshelio** [3nvi/gatsby-intl#5]
Hi,

I've kickstarted a project with your Gatsby starter and as far as language handling does it works great.

However, I want to have a section for authenticated users and I'm following this article: https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

in `gatsby-node.js` I have this:
```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  if (page.path.match(/^\/app/)) {
    page.matchPath = '/app/*'
    createPage(page)
  }
}
```

And if I go to `http://localhost:8000/app` I have indeed the app. However, I lose the ability to have languages. I'm wondering how I could handle multilingual in the app, something like this: `http://localhost:8000/app/profile/en` or `http://localhost:8000/app/profile/fr`?

**Comment by 3nvi** [comment]
Hey there,

`gatsby-intl` aims to give you multi-language static files and not "dynamic routes"  per say. From my understanding, you have a single static `/pages/app.jsx` file and you want to add dynamic routes to it (so you can have `/app/something/` and `/app/something-else/`). 

This package would be able to create multi-language variations of the `/pages/app.jsx` static page and "stop there". This means that you would be able to create stuff like `/app/en/something/` and `/app/en/something-else/` (the language-part is **right  after** the `/app/` part).

To do so, just make sure that `gastby-intl` runs before the custom `onCreatePage` that you have. I see that gatsby provides [a plugin for client  routes](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/), so you could use that in your `gatsby-config` right **after** the `gatsby-intl` definition.

Theoretically, what you describe in your ticket could work, but it might involve some hacking around, since the purpose of `gatsby-intl` is to handle pages that will end up in your `/build` folder (not "client ones"). Due to that, I think you best  bet is to "tie" `gatsby-intl` to the `/app/` page (which will exist in your `/build` folder if I'm understanding it correctly) and add your client-path behavior after that.

Is there a chance you can try  that  and get back to me?

**Comment by alveshelio** [comment]
Hi @3nvi ,

Thank you very much for the fast return. I'm definitely going to try it and get back to you :)

Once again, thank you so much.

**Comment by 3nvi** [comment]
You're welcome. Wish I had more time to try it out myself :/

**Comment by alveshelio** [comment]
Hi,

So I've actually tried with the plugin `gatsby-plugin-create-client-paths`. I've placed it after gatsby-intl but it doesn't seem to have the effect expected :)

This is what I have in `gatsby-config.js`

```
module.exports = {
  // site metadata
  plugins: [
    // some other plugins
    {
      resolve: `@3nvi/gatsby-theme-intl`,
      options: {
        supportedLanguages: ['en', 'fr'],
        defaultLanguage: 'en',
        i18nextConfig: {
          resources,
        },
      },
    },
    {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
    },
    // some more plugins
  ],
}
```

With this set up, now if I try this URL: `http://localhost:8000/app` it automatically redirects me to `http://localhost:8000/en/app` and I get a blank page.

Does it means that there would be need for some work on the gatsby-intl plugin or the starter? Is there any way I could help. I'm not really sure where to start looking :)

I don't have much experience with Gatsby but if there's anything I can help with :) just point me to where I should start looking and I'll see if I can get anything to work :)

Thank you again.

**Comment by 3nvi** [comment]
Hey there,

from my understanding, right now the `{ prefixes: ['/app/*'] },` is no longer correct. Since all pages will be in the format `/{lang}/app/*`, you have to make `gatsby-plugin-create-client-paths` aware of the new format.

With this in mind can you try replacing

```jsx
{
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
},
```

with 

```js
{
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/en/app/*`, `/fr/app/*`] }, //  you can also create a regex for it
},
```

If that doesn't do  the trick, I'll try and spend some time tomorrow  and experiment myself to help you out.

Let me know!

**Comment by alveshelio** [comment]
Thank you again for your fast reply :) I've tried and it doesn't work.

**Comment by alveshelio** [comment]
This is the repo of the project in case you want to take a look at it: https://github.com/Circularity-IO/circularity-io/tree/feature/authenticated-routes

I'm just trying to get the client-only routes working before doing any more work on it :)

**Comment by 3nvi** [comment]
Sure thing, thanks! I'll get back to you shortly

**Comment by 3nvi** [comment]
Hey again,

the problem lies in this line [here](https://github.com/Circularity-IO/circularity-io/blob/8992f621ec4a361d1b97c516d88b7b031027ed7a/src/pages/app.tsx#L10)

By adding

```js
{
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/en/app/*`, `/fr/app/*`] }, //  you can also create a regex for it
},
```

you are telling Gatsby "every page that starts with `/en/app/` or `/fr/app` will be client-side only), but then on your Router you say:

```jsx
<Router basepath="/app">
  ...
</Router>
```

which tells `@reach/router` to only match components starting with `/app` (and not `/en/app/`). What you need to do is to the same thing you did on your Gatsby config, but  on the router side. You can do so by adding this:

```jsx
const App = () => {
const { matchPath } = usePageContext();

return (
    <Layout>
      <Router basepath={matchPath}>
        <PrivateRoute path="/profile" component={Profile} />
        <Dashboard path="/" />
      </Router>
    </Layout>
  )
}
```

`matchPath` is provided by `gatsby-plugin-create-client-paths` and is only defined for client-only pages. Its value will be either `/en/app/*` or `/fr/app/*` depending on the current page.

Alternatively, you can achieve the same thing by using stuff that are defined by `gatsby-plugin-intl`, specifically `lang` and `originalPath` and do this:

```jsx
const App = () => {
const { lang, originalPath } = usePageContext(); 

return (
    <Layout>
      <Router basepath={`/${lang}${originalPath}`}>
        <PrivateRoute path="/profile" component={Profile} />
        <Dashboard path="/" />
      </Router>
    </Layout>
  )
}
```

where `/${lang}${originalPath}` would create `/en/app/` or `/el/app/`. 

To wrap up, the answer would be to add the proper "language prefix" to the `Router` defined in your `app.js` :)

P.S. I've personally  verified that it works for me, but let me know how it goes. If for some reason it doesn't work, I'll upload a replication repo to help out

**Comment by alveshelio** [comment]
Thank you very much for your precious help. I didn't catch the basePath in the router. I'm going to implement your solution.

Once again, a big THANK YOU for your precious help.

**Comment by alveshelio** [comment]
So I was able to make it partly work :)

Your solution fixes the issue with the client-only routes, if I enter the URL by hand everything is OK. 

So both `http://localhost:8000/en/app` and `http://localhost:8000/fr/app` display the page correctly. However, if I'm on `http://localhost:8000/en/app` and I switch language to FR then I get 'http://localhost:8000/en/fr/app` and the app breaks. What it's weird is that if I mouse hover the link to switch to French, the URL is correct. I have indeed `http://localhost:8000/fr/app` but somehow we are injecting `/en` or `/fr`

Something that I've also noticed is that if I copy the url `http://localhost:8000/en/app` and paste it in the browser, it gets redirected to `http://localhost:8000/en/en/app`, we have the same behaviour when we try to switch languages in `/app`.

**Comment by 3nvi** [comment]
It has to do with the trailing slash. Let me see if it's a misconfiguration or a bug in the plugin

**Comment by alveshelio** [comment]
Also, when I open localhost for the first time I get these errors:
```
index.js:2177 The route "/" matches both a page and a redirect; this is probably not intentional.
__stack_frame_overlay_proxy_console__ @ index.js:2177
r @ react_devtools_backend.js:6
maybeRedirect @ navigation.js:24
init @ navigation.js:157
(anonymous) @ root.js:39
./.cache/root.js @ root.js:129
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
(anonymous) @ app.js:92
Promise.then (async)
(anonymous) @ app.js:86
Promise.then (async)
(anonymous) @ app.js:24
./.cache/app.js @ app.js:17
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
0 @ theme.ts:3
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:2177 The route "/" matches both a page and a redirect; this is probably not intentional. 
    at RouteUpdates (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at EnsureResources (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at LocationHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:24895:23)
    at Root
    at ColorModeProvider (http://localhost:8000/commons.js:10982:20)
    at ThemeProvider
    at ThemeProvider (http://localhost:8000/commons.js:18780:20)
    at I18nextProvider (http://localhost:8000/commons.js:94847:19)
    at Auth0Provider (http://localhost:8000/commons.js:109198:23)
    at StaticQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at _default
```

```
index.js:2177 The route "/" matches both a page and a redirect; this is probably not intentional. 
    at RouteUpdates (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at EnsureResources (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at LocationHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:24895:23)
    at Root
    at ColorModeProvider (http://localhost:8000/commons.js:10982:20)
    at ThemeProvider
    at ThemeProvider (http://localhost:8000/commons.js:18780:20)
    at I18nextProvider (http://localhost:8000/commons.js:94847:19)
    at Auth0Provider (http://localhost:8000/commons.js:109198:23)
    at StaticQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:91837:10), <anonymous>:14:7)
    at _default
```

```
Warning: Cannot update a component (`IndexPage`) while rendering a different component (`PageRenderer`). To locate the bad setState() call inside `PageRenderer`, follow the stack trace as described in https://fb.me/setstate-in-render
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:56)
    in RouteHandler (at root.js:78)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:69)
    in RouteUpdates (at root.js:68)
    in EnsureResources (at root.js:66)
    in LocationHandler (at root.js:124)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:123)
    in Root (at root.js:131)
    in ColorModeProvider (at gatsby-browser.js:12)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (at gatsby-browser.js:9)
    in I18nextProvider
    in Auth0Provider (at gatsby-browser.js:10)
    in StaticQueryStore (at root.js:138)
    in _default (at app.js:94)
```

![image](https://user-images.githubusercontent.com/8176422/83335937-28a98a00-a27e-11ea-982f-2162cce1d8ff.png)
![image](https://user-images.githubusercontent.com/8176422/83335942-33fcb580-a27e-11ea-95fc-b7686a2be8fa.png)

**Comment by 3nvi** [comment]
Yeah there is a clash between local routes & the plugin. I found a solution butt I want to test it out a bit before I patch it.

Will most likely release a bugfix version for that tomorrow

**Comment by 3nvi** [comment]
Hey @alveshelio ,

 I fixed a small issue that existed in the library.

Please install the latest version of the packages and follow the [instructions here](https://github.com/3nvi/gatsby-intl/blob/master/packages/gatsby-theme-intl/README.md#client-only-routes) to configure them.

I've personally  tested it against your project and all worked fine. 

Let me know if all's ok from your side as well

**Comment by alveshelio** [comment]
Hi @3nvi,

So I've updated `@3nvi/gatsby-theme-intl` to version `0.4.9` and I've followed your instructions to have include `gatsby-plugin-create-client-paths` before `gastby-theme-intl` and I've updated the path in Router and I'm still having the same issues :(. I've pushed my changes, here's the commit: https://github.com/Circularity-IO/circularity-io/commit/f47db260b935821651d1e59fc166f3fcbbac0304

**Comment by 3nvi** [comment]
Hey @alveshelio ,

pulled it and everything works fine from my end. I see one tiny bug, in that the language picker uses `Link` from `@3nvi/gatsby-theme-intl`, while [the starter](https://github.com/3nvi/gatsby-intl/blob/master/packages/gatsby-starter-intl/src/components/header.js) uses the `GatsbyLink` (this is the only place where we want the Link from Gatsby instead of the one in this package, since we want to skip the automatic language prefixing that  the `Link` from `@3nvi/gatsby-theme-intl` does. That's the reason you see `/en/en/app` links).

Other than that, make sure you delete your top level `.cache` in case gatsby cached some old plugin. Having those done, I see the app working just fine :)

Can you verify?

**Comment by alveshelio** [comment]
Hi @3nvi,

Thank you very much, it does work indeed. I just need to figure out the issues with the errors in the console.

Once again, thank you very much for your help.
